### ISSUE TITLE
Can we remove moduleclass_sfx?

### ISSUE THREAD

**Issue by uglyeoin** [joomla-extensions/boilerplate#29]
@astridx According to this https://docs.joomla.org/J4.x:Creating_a_Simple_Module we no longer need $moduleclass_sfx = htmlspecialchars($params->get('moduleclass_sfx')); due to https://github.com/joomla/joomla-cms/pull/17447.  Since people link to this as a resource it should be right. 

I'm flagging this but I don't know if I'm doing the right thing as my code skills are not strong enough.  Close it if I'm wrong.

**Comment by astridx** [comment]
@uglyeoin  You are right. In the sample files (https://github.com/astridx/boilerplate/tree/tutorial/tutorial/modules) it should be fine.

@roland-d i think you are the maintainer of this repository, right?

**Comment by roland-d** [comment]
@astridx Correct, I am the maintainer of this repository.
@uglyeoin Thank you for pointing this out. I need to take a look what can be done with this. We don't have a distinction between a Joomla 3 and Joomla 4 module at this point. How useful/used is the `moduleclass_sfx` in Joomla 3? Do you know?

**Comment by uglyeoin** [comment]
I think it is quite used in J3.  I know I use it a fair bit, I can't speak on behalf of a few million users, so I will anyway.  Let's keep it for J3.  But this is a J4 module right?  I was linked to from the tutorial here: https://docs.joomla.org/J4.x:Creating_a_Simple_Module but why don't we just change that link to here instead: https://github.com/astridx/boilerplate/tree/tutorial/tutorial/modules then there's no issues, right?

**Comment by roland-d** [comment]
I can add a version check around it, this should also make it clear that it is only for Joomla 3. As an extra add a comment that it is no longer used in J4.

**Comment by uglyeoin** [comment]
Honestly, I'm not knowledgable enough to tell you if that's the right answer.  Wish I could help, but someone smarter than I should answer it - you're smarter, you can decide :)

**Comment by roland-d** [comment]
I have added a comment above the line, that should be clear enough.
