### ISSUE TITLE
folder controllers expected to be named controller

### ISSUE THREAD

**Issue by ThomasFinnern** [joomla-extensions/boilerplate#31]
Comparing folder name "controller **(s)**" in other components in J!4 i didn't find a path with multiple form of controller

Path on my PC from main
...\boilerplate.roland-d\component\administrator\components\com_foo\controllers

Same for models, tables and views. Is it intentionally ?

**Comment by roland-d** [comment]
@ThomasFinnern I never saw this issue before so that is why a late reply. In Joomla 3 the folders are always plural. Where would you expect the folders to be named different?

**Comment by roland-d** [comment]
The J4 version does have singular names, see https://github.com/joomla-extensions/boilerplate/tree/2019.3/src/j4component or is it somewhere else I am missing?

**Comment by ThomasFinnern** [comment]
Probaply i stumbled into the wrong branch
